name = "SurvieAM"
uuid = "ab8d3bd5-ec27-47ba-bfe2-f8587b192ebb"
authors = ["Chevaux-Rochas"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
